import * as React from "react";
import { Document, Page, View, Text, StyleSheet } from "@react-pdf/renderer";

import { BRAND_FONT } from "./fonts";

const TEAL = "#1ab6b6";
const INK = "#1a1a1a";
const MUTED = "#5f6b76";
const BLACK = "#000000";
const HAIRLINE = "#d9dee3";

type Block =
  | { type: "h1" | "h2" | "h3" | "p" | "li"; text: string };

// Strip common inline markdown so it renders as plain PDF text.
const clean = (s: string) =>
  s
    .replace(/\*\*(.+?)\*\*/g, "$1")
    .replace(/(^|[^*])\*(?!\s)(.+?)\*/g, "$1$2")
    .replace(/\[(.+?)\]\((.+?)\)/g, "$1 ($2)")
    .replace(/`(.+?)`/g, "$1")
    .trim();

/** Parse a markdown string into a flat list of simple blocks for the PDF. */
export function parseMarkdown(md: string): Block[] {
  const out: Block[] = [];
  for (const raw of md.split(/\r?\n/)) {
    const line = raw.trim();
    if (!line) continue;
    let m: RegExpMatchArray | null;
    if ((m = line.match(/^###\s+(.*)/))) out.push({ type: "h3", text: clean(m[1]) });
    else if ((m = line.match(/^##\s+(.*)/))) out.push({ type: "h2", text: clean(m[1]) });
    else if ((m = line.match(/^#\s+(.*)/))) out.push({ type: "h1", text: clean(m[1]) });
    else if ((m = line.match(/^[-*+]\s+(.*)/))) out.push({ type: "li", text: clean(m[1]) });
    else if ((m = line.match(/^\d+\.\s+(.*)/))) out.push({ type: "li", text: clean(m[1]) });
    else if (/^[-–—]{3,}$/.test(line)) continue;
    else out.push({ type: "p", text: clean(line) });
  }
  return out;
}

const styles = StyleSheet.create({
  page: { fontFamily: BRAND_FONT, fontSize: 10, color: INK, lineHeight: 1.45, paddingBottom: 54 },
  header: {
    backgroundColor: BLACK,
    paddingHorizontal: 34,
    paddingVertical: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  logoMark: { fontSize: 22, fontWeight: 700, color: TEAL, letterSpacing: -1 },
  headerTag: { fontSize: 12, fontWeight: 700, color: "#ffffff" },
  body: { paddingHorizontal: 34, paddingTop: 18 },
  title: { fontSize: 17, fontWeight: 700, color: INK },
  sub: { fontSize: 9, color: MUTED, marginTop: 2, marginBottom: 6 },
  rule: { borderBottomWidth: 1, borderBottomColor: HAIRLINE, marginBottom: 12 },
  h1: { fontSize: 14, fontWeight: 700, color: INK, marginTop: 12, marginBottom: 4 },
  h2: { fontSize: 12, fontWeight: 700, color: TEAL, marginTop: 12, marginBottom: 3 },
  h3: { fontSize: 10.5, fontWeight: 700, color: INK, marginTop: 8, marginBottom: 2 },
  p: { fontSize: 10, color: INK, marginBottom: 5 },
  liRow: { flexDirection: "row", marginBottom: 3, paddingLeft: 4 },
  liMark: { width: 10, color: TEAL },
  liText: { flex: 1, fontSize: 10, color: INK },
  footer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: BLACK,
    paddingHorizontal: 34,
    paddingVertical: 10,
  },
  footerText: { color: "#c7ccd1", fontSize: 7.5 },
});

export function DeepDiveDocument({
  title,
  markdown,
  generatedOn,
}: {
  title: string;
  markdown: string;
  generatedOn: string;
}) {
  const blocks = parseMarkdown(markdown);
  return (
    <Document title={`${title} — Deep Dive`} author="CDG Leisure">
      <Page size="A4" style={styles.page}>
        <View style={styles.header} fixed>
          <Text style={styles.logoMark}>cdg</Text>
          <Text style={styles.headerTag}>DEEP DIVE</Text>
        </View>

        <View style={styles.body}>
          <Text style={styles.title}>{title}</Text>
          <Text style={styles.sub}>AI company research · generated {generatedOn}</Text>
          <View style={styles.rule} />

          {blocks.map((b, i) => {
            if (b.type === "li") {
              return (
                <View key={i} style={styles.liRow} wrap={false}>
                  <Text style={styles.liMark}>•</Text>
                  <Text style={styles.liText}>{b.text}</Text>
                </View>
              );
            }
            return (
              <Text key={i} style={styles[b.type]}>
                {b.text}
              </Text>
            );
          })}
        </View>

        <View style={styles.footer} fixed>
          <Text style={styles.footerText}>
            Generated by CliftonAi-CRM for internal use. AI-assisted research — verify
            key facts before acting. cdgleisure.com
          </Text>
        </View>
      </Page>
    </Document>
  );
}
