/**
 * Render `supabase/seeds/lewiscraig_listings.json` (from scrape-lewiscraig.ts)
 * into `supabase/seeds/lewiscraig_listings.sql` — an idempotent Market Intel
 * seed for the demo agency's `disposals` table.
 *
 *   node scripts/generate-lewiscraig-seed.ts
 *
 * Unlike the CDG seed (which owns the whole book and wipes the agency's
 * disposals first), this only ever replaces rows where source='lewiscraig' —
 * intel stock layers on top of CDG's own instructions. Rows are stamped
 * listing_type='intel' so they render the unbranded PDF and surface under the
 * Market Intel silo. No lead agent is assigned: the marketing agent is the
 * partner's own (kept in agent_name/email/phone).
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

import type { DisposalInsert } from "../src/lib/disposals/cdg.ts";

const __dirname = dirname(fileURLToPath(import.meta.url));
const SEEDS = join(__dirname, "..", "supabase", "seeds");
const rows = JSON.parse(
  readFileSync(join(SEEDS, "lewiscraig_listings.json"), "utf8"),
) as DisposalInsert[];

const payload = JSON.stringify(rows);
if (payload.includes("$lc$")) throw new Error("Payload collides with the $lc$ dollar-quote tag.");

const sql = `-- ─────────────────────────────────────────────────────────────────────────────
-- Lewis Craig available stock → demo agency \`disposals\` as MARKET INTEL.
-- GENERATED by scripts/generate-lewiscraig-seed.ts from lewiscraig_listings.json —
-- do not hand-edit; re-run the scraper + generator to refresh.
--
--   ${rows.length} live listings scraped from lewiscraig.co.uk
--   (src/lib/disposals/lewiscraig.ts). listing_type='intel' → unbranded PDF +
--   Market Intel silo. Only replaces rows where source='lewiscraig'.
-- ─────────────────────────────────────────────────────────────────────────────
do $$
declare
  demo_agency uuid;
  rec         jsonb;
  i           int := 0;
  payload     jsonb := $lc$${payload}$lc$::jsonb;
begin
  select id into demo_agency from public.agencies where name = 'CDG demo' limit 1;
  if demo_agency is null then
    raise exception 'Demo agency "CDG demo" not found — run dummy_data.sql first.';
  end if;

  -- Replace only this source's rows; CDG's own book is untouched.
  delete from public.disposals where agency_id = demo_agency and source = 'lewiscraig';

  for rec in select * from jsonb_array_elements(payload) loop
    i := i + 1;
    insert into public.disposals (
      agency_id, source, source_ref, source_url, status, listing_type,
      title, summary, address_line, area, city, postcode, lat, lng,
      property_type, use_class, disposal_type, to_let, for_sale,
      rent_pa, rent_raw, rent_period, premium, premium_raw, guide_price, price_qualifier,
      size_sqft, size_sqm, covers_internal, covers_external, floors,
      description, location_description, key_features, sections,
      agent_name, agent_email, agent_phone,
      images, brochure_url
    ) values (
      demo_agency,
      'lewiscraig', rec->>'source_ref', rec->>'source_url', rec->>'status', 'intel',
      rec->>'title', rec->>'summary', rec->>'address_line', rec->>'area', rec->>'city',
      rec->>'postcode', (rec->>'lat')::double precision, (rec->>'lng')::double precision,
      rec->>'property_type', rec->>'use_class', rec->>'disposal_type',
      (rec->>'to_let')::boolean, (rec->>'for_sale')::boolean,
      (rec->>'rent_pa')::numeric, rec->>'rent_raw', rec->>'rent_period',
      (rec->>'premium')::numeric, rec->>'premium_raw', (rec->>'guide_price')::numeric,
      rec->>'price_qualifier',
      (rec->>'size_sqft')::numeric, (rec->>'size_sqm')::numeric,
      (rec->>'covers_internal')::int, (rec->>'covers_external')::int,
      coalesce(rec->'floors', '[]'::jsonb),
      rec->>'description', rec->>'location_description',
      coalesce(array(select jsonb_array_elements_text(rec->'key_features')), '{}'::text[]),
      coalesce(rec->'sections', '[]'::jsonb),
      rec->>'agent_name', rec->>'agent_email', rec->>'agent_phone',
      coalesce(rec->'images', '[]'::jsonb), rec->>'brochure_url'
    );
  end loop;

  raise notice 'Loaded % Lewis Craig intel listings into agency %.', i, demo_agency;
end $$;
`;

const out = join(SEEDS, "lewiscraig_listings.sql");
writeFileSync(out, sql);
console.log(`Wrote ${rows.length} listings → ${out} (${(sql.length / 1024).toFixed(0)} KB)`);
