/**
 * Render an intel source's scraped JSON (`supabase/seeds/{source}_listings.json`)
 * into an idempotent SQL seed (`supabase/seeds/{source}_listings.sql`) for the
 * demo agency's `disposals` table.
 *
 *   node scripts/generate-intel-seed.ts --source shelleysandzer
 *
 * Like the Lewis Craig seed (whose generator this generalises), it only ever
 * replaces rows where source matches — intel stock layers on top of CDG's own
 * instructions. Rows are stamped listing_type='intel' so they render the
 * unbranded PDF and surface under the Market Intel silo.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

import type { DisposalInsert } from "../src/lib/disposals/cdg.ts";

const sourceArg = process.argv.indexOf("--source");
const source = sourceArg !== -1 ? process.argv[sourceArg + 1] : null;
if (!source || !/^[a-z0-9_]+$/.test(source)) {
  console.error("Usage: node scripts/generate-intel-seed.ts --source <source-id>");
  process.exit(1);
}

const __dirname = dirname(fileURLToPath(import.meta.url));
const SEEDS = join(__dirname, "..", "supabase", "seeds");
const rows = JSON.parse(
  readFileSync(join(SEEDS, `${source}_listings.json`), "utf8"),
) as DisposalInsert[];

const payload = JSON.stringify(rows);
if (payload.includes("$in$")) throw new Error("Payload collides with the $in$ dollar-quote tag.");

const sql = `-- ─────────────────────────────────────────────────────────────────────────────
-- ${source} available stock → demo agency \`disposals\` as MARKET INTEL.
-- GENERATED by scripts/generate-intel-seed.ts from ${source}_listings.json —
-- do not hand-edit; re-run the scraper + generator to refresh.
--
--   ${rows.length} live listings (src/lib/disposals/${source}.ts).
--   listing_type='intel' → unbranded PDF + Market Intel silo.
--   Only replaces rows where source='${source}'.
-- ─────────────────────────────────────────────────────────────────────────────
do $$
declare
  demo_agency uuid;
  rec         jsonb;
  i           int := 0;
  payload     jsonb := $in$${payload}$in$::jsonb;
begin
  select id into demo_agency from public.agencies where name = 'CDG demo' limit 1;
  if demo_agency is null then
    raise exception 'Demo agency "CDG demo" not found — run dummy_data.sql first.';
  end if;

  -- Replace only this source's rows; everything else is untouched.
  delete from public.disposals where agency_id = demo_agency and source = '${source}';

  for rec in select * from jsonb_array_elements(payload) loop
    i := i + 1;
    insert into public.disposals (
      agency_id, source, source_ref, source_url, status, listing_type,
      title, summary, address_line, area, city, postcode, lat, lng,
      property_type, use_class, disposal_type, to_let, for_sale,
      rent_pa, rent_raw, rent_period, premium, premium_raw, guide_price, price_qualifier,
      size_sqft, size_sqm, covers_internal, covers_external, floors,
      description, location_description, key_features, sections,
      agent_name, agent_email, agent_phone,
      images, brochure_url
    ) values (
      demo_agency,
      '${source}', rec->>'source_ref', rec->>'source_url', rec->>'status', 'intel',
      rec->>'title', rec->>'summary', rec->>'address_line', rec->>'area', rec->>'city',
      rec->>'postcode', (rec->>'lat')::double precision, (rec->>'lng')::double precision,
      rec->>'property_type', rec->>'use_class', rec->>'disposal_type',
      (rec->>'to_let')::boolean, (rec->>'for_sale')::boolean,
      (rec->>'rent_pa')::numeric, rec->>'rent_raw', rec->>'rent_period',
      (rec->>'premium')::numeric, rec->>'premium_raw', (rec->>'guide_price')::numeric,
      rec->>'price_qualifier',
      (rec->>'size_sqft')::numeric, (rec->>'size_sqm')::numeric,
      (rec->>'covers_internal')::int, (rec->>'covers_external')::int,
      coalesce(rec->'floors', '[]'::jsonb),
      rec->>'description', rec->>'location_description',
      coalesce(array(select jsonb_array_elements_text(rec->'key_features')), '{}'::text[]),
      coalesce(rec->'sections', '[]'::jsonb),
      rec->>'agent_name', rec->>'agent_email', rec->>'agent_phone',
      coalesce(rec->'images', '[]'::jsonb), rec->>'brochure_url'
    );
  end loop;

  raise notice 'Loaded % ${source} intel listings into agency %.', i, demo_agency;
end $$;
`;

const out = join(SEEDS, `${source}_listings.sql`);
writeFileSync(out, sql);
console.log(`Wrote ${rows.length} listings → ${out} (${(sql.length / 1024).toFixed(0)} KB)`);
